### ISSUE TITLE
Readme hırsızına her tokat like

### ISSUE THREAD

**Issue by sudis** [wioenena-q/wio.db#2]
öncelikle sa benim readmem calınıyor nerde dövlət nerde haq nerde huquq kardeşim aparık məni.

**Comment by sudis** [comment]
Çaldılar aga çaldılar canımdan can gitti aga.

**Comment by lunexdev** [comment]
bi readme dosyası alt tarafı fazlamı büyüttün sanki

**Comment by sudis** [comment]
beni öldürüp canımı alsalardı yeterdi abi ama readmem gitti anlatabiliyo muyum abi

**Comment by takipsizad** [comment]
linki at?

**Comment by wioenena-q** [comment]
Lan kullandığın readme her herde vardı değiştirdim artık sus be

**Comment by lunexdev** [comment]
adam ol wio zaten değişicektin

**Comment by sudis** [comment]
eyv sorunum çözüldü kardeşim Çana bas zili aç (s)abun ol.

**Comment by Umut-Ozkan** [comment]
sude lafı koydu EQWLKJSHDKFJASHDFLKJSADFA

**Comment by wioenena-q** [comment]
Çoluk çocukla uğraşıoz yienim

**Comment by zukrein71** [comment]
olm readme hırsızlığı ne alakka akjsdhkjashdkjasdh

**Comment by sudis** [comment]
Sa ben yokken çakallar Ürük ne bu iş

**Comment by zukrein71** [comment]
ya abla git yat bu saatte nabıyon yaw

**Comment by sudis** [comment]
Benim readmemin kanı yerde.kalmadı

**Comment by wioenena-q** [comment]
Ortam malı olan readme'yi de sahiplenmezsin be :D

**Comment by zukrein71** [comment]
senin readme ne at baakim

**Comment by wioenena-q** [comment]
Bi ara başkasından aldığım genelde herkesin kullandığı readmeyi kullandım diye çaldık olduk :D

**Comment by wioenena-q** [comment]
Değiştirdim susarsın attık

**Comment by sudis** [comment]
savaşı kazandık kardesim bu savas bizimdir

**Comment by wioniqle-q** [comment]
Sa bacılar

**Comment by sudis** [comment]
As kardes bu readme hırsızını tanıyon mu
